### ISSUE TITLE
[bug]: Error in Gui -> Adapter page -> v7.1.1

### ISSUE THREAD

**Issue by diamand2k22** [ioBroker/ioBroker.admin#2684]
### No existing issues.

- [X] There is no existing issue for my problem.

### Describe the bug

Trying to acess adapter page a red screen appears with "Error in GUI"

### To Reproduce

1. Go to iobroker admin
2. Press on adapters
3.  Page is loading, after some seconds -> "Error in Gui" appears

### Expected behavior

Adapter page should be shown

### Screenshots & Logfiles

If in the second line you will see at :3000/static/js/main.chunk.js:36903 and not the normal file name,
please try to reproduce an error with opened browser console. In this case the special "map" files will be loaded and the developers can see the real name of functions and files.
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Error%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Error%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at va (http://147.121.154.78:8078/static/js/5096.3a6e8bdb.chunk.js:2:49950)
    at e (http://147.121.154.78:8078/static/js/5096.3a6e8bdb.chunk.js:2:54963)
    at ko (http://147.121.154.78:8078/static/js/5096.3a6e8bdb.chunk.js:2:73156)
    at xi (http://147.121.154.78:8078/static/js/5096.3a6e8bdb.chunk.js:2:122082)
    at bs (http://147.121.154.78:8078/static/js/5096.3a6e8bdb.chunk.js:2:109361)
    at vs (http://147.121.154.78:8078static/js/5096.3a6e8bdb.chunk.js:2:109289)
    at gs (http://147.121.154.78:8078/static/js/5096.3a6e8bdb.chunk.js:2:109152)
    at as (http://147.121.154.78:8078/static/js/5096.3a6e8bdb.chunk.js:2:105932)
    at ls (http://147.121.154.78:8078/static/js/5096.3a6e8bdb.chunk.js:2:104483)
    at S (http://147.121.154.78:8078/static/js/5096.3a6e8bdb.chunk.js:2:131248)
    at MessagePort.T (http://147.121.154.78:8078/static/js/5096.3a6e8bdb.chunk.js:2:131782)

### Adapter version

v7.1.1

### js-controller version

v20.17.0

### Node version

10.8.2

### Operating system

raspbian os

**Comment by foxriver76** [comment]
Can you try this `If in the second line you will see at :3000/static/js/main.chunk.js:36903 and not the normal file name,
please try to reproduce an error with opened browser console. In this case the special "map" files will be loaded and the developers can see the real name of functions and files.`

**Comment by AlexW987** [comment]
I have the same issue since the update to 7.1.1_

`bootstrap.tsx:22 iobroker.admin@7.0.25
socket.io.js:66 [2024-09-20T11:03:57.082Z] Try to connect
App.tsx:992 Stored version: , new version: 7.1.1
HostsWorker.tsx:55 Connected: true
IntroCard.tsx:260 Translate: Link
App.tsx:1622 Error: timeout
    at Connection.ts:1094:28
    at r (helpers.ts:98:17)
(anonymous) @ console.ts:40
Za.onNews @ App.tsx:1622
await in Za.onNews
subscribeState @ Connection.ts:694
await in subscribeState
(anonymous) @ App.tsx:1199
Promise.then
(anonymous) @ App.tsx:1197
r @ helpers.ts:98
setTimeout
(anonymous) @ browserapierrors.ts:109
onReady @ App.tsx:1196
await in onReady
doLoadData @ Connection.ts:577
await in doLoadData
loadData @ Connection.ts:500
onPreConnect @ Connection.ts:433
(anonymous) @ Connection.ts:319
SocketClient.findAnswer @ socket.io.js:303
socket.onmessage @ socket.io.js:212
Show 8 more frames
Show less
console.ts:40 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Error%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at va (react-dom.production.min.js:135:60)
    at e (react-dom.production.min.js:145:372)
    at ko (react-dom.production.min.js:191:308)
    at xi (react-dom.production.min.js:293:9)
    at bs (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at gs (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at ls (react-dom.production.min.js:267:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
(anonymous) @ console.ts:40
co @ react-dom.production.min.js:188
a.componentDidCatch.t.callback @ react-dom.production.min.js:189
Wa @ react-dom.production.min.js:156
ki @ react-dom.production.min.js:260
bi @ react-dom.production.min.js:259
yi @ react-dom.production.min.js:258
(anonymous) @ react-dom.production.min.js:282
ws @ react-dom.production.min.js:280
ls @ react-dom.production.min.js:269
S @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
Show 12 more frames
Show less
`

**Comment by mcm1957** [comment]
Please redest with 7.1.2.

**Comment by foxriver76** [comment]
Can someone who has the problem please re-try with 7.1.3 (Beta version), if it is still happening I would need log from this version

**Comment by Michel83** [comment]
I have the same problem, how can i update to 7.1.3 via ssh ?

The visu off iobroker does not right start for change to beta

**Comment by foxriver76** [comment]
`iob url iobroker.admin@7.1.3`

**Comment by Michel83** [comment]
For me the same, error iss gone with 7.1.3

**Comment by foxriver76** [comment]
Perfect thanks for the Feedback

**Comment by diamand2k22** [comment]
> Perfect thanks for the Feedback

I can confirm that, error is gone with 7.3.1.
Thx
