### ISSUE TITLE
Error in Gui

### ISSUE THREAD

**Issue by Vrumfondel** [ioBroker/ioBroker.admin#1239]
The gui asked me to open a bug report here, so I do.
That's what I get after updating to the latest release of admin:
```
ChunkLoadError: Loading chunk 13 failed.function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}(error: http://10.1.1.151:8081/static/js/13.76eaf746.chunk.js)function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}    at Function.u.e (http://10.1.1.151:8081/:1:3981)function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}    at http://10.1.1.151:8081/static/js/main.c7f54a06.chunk.js:2:1065870function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}    at V (http://10.1.1.151:8081/static/js/5.11c30091.chunk.js:2:5685802)function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}    at Zi (http://10.1.1.151:8081/static/js/5.11c30091.chunk.js:2:5675986)function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}    at jl (http://10.1.1.151:8081/static/js/5.11c30091.chunk.js:2:5662647)function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}    at Sl (http://10.1.1.151:8081/static/js/5.11c30091.chunk.js:2:5662575)function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}    at Cl (http://10.1.1.151:8081/static/js/5.11c30091.chunk.js:2:5662438)function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}    at zl (http://10.1.1.151:8081/static/js/5.11c30091.chunk.js:2:5659404)function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}    at http://10.1.1.151:8081/static/js/5.11c30091.chunk.js:2:5608898function(e,t){return Object(Ie.jsxs)("div",{children:[e,Object(Ie.jsx)("br",{})]},t)}    at t.unstable_runWithPriority (http://10.1.1.151:8081/static/js/5.11c30091.chunk.js:2:5692108)
```

**Comment by Apollon77** [comment]
Newest admin 5.2.1 requires js-controller 3.3 ... is that on your system fulfilled?

**Comment by Vrumfondel** [comment]
AH - good point.
Isn't it possible to check this prerequisite before the update is allowed from the GUI?

**Comment by Apollon77** [comment]
Yes, there was an error in exactly that config, but should be fixed in the course of today

**Comment by numberdotone** [comment]
for me the same (an error), after updating to 

```
TypeError: o.getHours is not a function
    at new s (ObjectChart.js:160)
    at zc (react-dom.production.min.js:135)
    at Uo (react-dom.production.min.js:181)
    at Zi (react-dom.production.min.js:269)
    at jl (react-dom.production.min.js:250)
    at Sl (react-dom.production.min.js:250)
    at Cl (react-dom.production.min.js:250)
    at zl (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
```
while trying to reach the history data within the smartmeter device adapter

Admin adapter 5.2.1 after updating JS controller to 3.3.22
Node.js v14.18.2
NPM 6.14.15

**Comment by epcos71** [comment]
Same problem with getHours after opening an object property.

Admin Adapter: 5.2.2
js controller: 3.3.22
npm 6.14.8
nodejs 4.15.0

**Comment by Apollon77** [comment]
@numberdotone @epcos71 Your issue is a different one --> #1242

**Comment by epcos71** [comment]
@Apollon77 Big sorry!!! Da war die Tastatur wieder schneller als das Hirn... :)

**Comment by numberdotone** [comment]
@Apollon77 Thanks for the hint.

**Comment by GermanBluefox** [comment]
Duplicate to https://github.com/ioBroker/ioBroker.admin/issues/1242
