### ISSUE TITLE
[bug]: Admin 7.7.15 only loads exactly one time in Firefox 144.0 then only blank page visible

### ISSUE THREAD

**Issue by CommanderXXL** [ioBroker/ioBroker.admin#3290]
### No existing issues.

- [x] There is no existing issue for my problem.

### Describe the bug

After updating Admin to 7.7.15 the admin ui could not be reloaded in firefox 144.0. I only got a blank page. I tried to clear the caches and retried loading multiple times with only blank page. When using Chrome, or Firefox on Android (144.0.1), the page was loading normaly. I then tried to use a different IPv6 URL of my fritzbox "iobroker.fritz.box:8081" which worked to load the UI once. As soon as I reloaded the page, it was blank only again. After downgrade to 7.7.3, all works fine again.

### To Reproduce

1. Update Adapter to 7.7.15
2. Reload admin page in Firefox 144.0 (Desktop) (it works on Firefox on Android 144.0.1)
3. See blank page instead of admin UI

### Expected behavior

When loading admin page, I see admin UI instead of blank page

### Screenshots & Logfiles

Nothing special

### Adapter version

7.7.15

### js-controller version

7.0.7

### Node version

22.21.0

### Operating system

Raspian Trixie

**Comment by skvarel** [comment]
Same here with chrome browser.

**Comment by CommanderXXL** [comment]
@sammie76-2:
Do this:
cd /opt/iobroker
npm install iobroker.admin@7.7.3 --production

**Comment by mcm1957** [comment]
> Same here with chrome browser.

7.7.15 Works normally with chrome and edge here.

**Comment by sammie76-2** [comment]
> ad ALL
> 
> Please attach a console log (F12) if UI is not working normally.

I am getting this error in javascript console (macOS Tahoe, Safari):

_Unhandled Promise Rejection: TypeError: e is not a function. (In 'e()', 'e' is false)_
